<a href="https://colab.research.google.com/github/mefy-Aruna/Face-App/blob/master/Classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import pandas as pd
# import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [99]:
df = pd.read_csv(r'KNN_dataset.csv')

In [11]:
df

0  0.0  56.0   3.5  ...        50.0        17.0       207.0  1.0
0      1  0.0  72.0   4.6  ...   68.675596   41.478343  275.919817  1.0
1      2  0.0  72.0  16.5  ...   80.000000   42.000000  651.000000  1.0
2      3  0.0  77.0   4.9  ...  187.820464  198.913673  340.157876  1.0
3      4  0.0  77.0   3.0  ...   56.314318   40.091000  220.000000  1.0
4      5  0.0  74.0   5.3  ...   68.805692   27.000000  117.000000  1.0
..   ...  ...   ...   ...  ...         ...         ...         ...  ...
272  273  1.0  40.0   5.6  ...   78.000000   20.000000  244.218394  0.0
273  274  0.0  26.0   4.7  ...  110.000000   93.000000  175.000000  0.0
274  275  1.0  44.0  15.7  ...   99.147738   36.355230  272.000000  0.0
275  276  1.0  41.0  12.0  ...  201.000000   14.000000  266.000000  0.0
276  277  0.0  53.0  17.9  ...   81.998967   32.051869  258.000000  0.0

[277 rows x 17 columns]

In [100]:
x = df.iloc[:, 1:16].values
y = df.iloc[:, 16].values

In [92]:
x


array([[  0.        ,  72.        ,   4.6       , ...,  68.67559572,
         41.47834349, 275.91981709],
       [  0.        ,  72.        ,  16.5       , ...,  80.        ,
         42.        , 651.        ],
       [  0.        ,  77.        ,   4.9       , ..., 187.82046422,
        198.91367303, 340.15787572],
       ...,
       [  1.        ,  44.        ,  15.7       , ...,  99.14773818,
         36.35523013, 272.        ],
       [  1.        ,  41.        ,  12.        , ..., 201.        ,
         14.        , 266.        ],
       [  0.        ,  53.        ,  17.9       , ...,  81.99896681,
         32.0518687 , 258.        ]])

In [ ]:
######### KNN IMPUTED DATASET


////////////////////////////

In [31]:
#@title CLASSIFIER1:KNN


In [119]:
# Train Test Split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier



In [120]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [130]:
# Preprocessing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [131]:
KNNclassifier = KNeighborsClassifier(n_neighbors = 7)
KNNclassifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [132]:
y_pred = KNNclassifier.predict(x_test)

In [133]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('KNN acc:',accuracy_score(y_test, y_pred))

[[11  8]
 [ 4 33]]
              precision    recall  f1-score   support

         0.0       0.73      0.58      0.65        19
         1.0       0.80      0.89      0.85        37

    accuracy                           0.79        56
   macro avg       0.77      0.74      0.75        56
weighted avg       0.78      0.79      0.78        56

KNN acc: 0.7857142857142857


In [117]:
#@title CLASSIFIER 2:DECISION TREE





In [107]:
#from sklearn.model_selection import train_test_split
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [153]:
from sklearn.tree import DecisionTreeClassifier
Decclassifier = DecisionTreeClassifier(criterion="entropy", max_depth = 9)
Decclassifier 

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=9, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [154]:

Decclassifier.fit(x_train,y_train)
y_pred = Decclassifier.predict(x_test)

In [155]:
from sklearn import metrics
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, y_pred))

DecisionTrees's Accuracy:  0.75


In [156]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('DecisionTree acc:',accuracy_score(y_test, y_pred))

[[11  8]
 [ 6 31]]
              precision    recall  f1-score   support

         0.0       0.65      0.58      0.61        19
         1.0       0.79      0.84      0.82        37

    accuracy                           0.75        56
   macro avg       0.72      0.71      0.71        56
weighted avg       0.74      0.75      0.75        56

DecisionTree acc: 0.75


In [ ]:
#@title CLASSIFIER 3:SVM


In [162]:

# Polynomial Kernel
from sklearn.svm import SVC   # Support Vector Classifier
SVMclassifier = SVC(kernel ='rbf')
SVMclassifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [163]:
y_pred = SVMclassifier.predict(x_test)

In [164]:
# Evaluating the Algorithm
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[11  8]
 [ 2 35]]
              precision    recall  f1-score   support

         0.0       0.85      0.58      0.69        19
         1.0       0.81      0.95      0.88        37

    accuracy                           0.82        56
   macro avg       0.83      0.76      0.78        56
weighted avg       0.82      0.82      0.81        56

0.8214285714285714


In [ ]:
#@title Classifier 4: Random Forest 


In [211]:
# Train the Algorithm
from sklearn.ensemble import RandomForestClassifier
RFclassifier = RandomForestClassifier(n_estimators = 100)
RFclassifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [212]:

y_pred = RFclassifier.predict(x_test)

In [213]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[14  5]
 [ 3 34]]
              precision    recall  f1-score   support

         0.0       0.82      0.74      0.78        19
         1.0       0.87      0.92      0.89        37

    accuracy                           0.86        56
   macro avg       0.85      0.83      0.84        56
weighted avg       0.86      0.86      0.86        56

0.8571428571428571


In [ ]:
#@title Classifier 5: Random Forest regressor


In [214]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [216]:
forest = RandomForestRegressor(n_estimators=100)

In [222]:
cross_val1 = cross_val_score(forest, x_train,y_train, cv=56)  

In [223]:
forest = forest.fit(x_train, y_train)

In [224]:
y_pred = forest.predict(x_test)

In [226]:
#print(confusion_matrix(y_test, y_pred))
#print(classification_report(y_test, y_pred))
#print(accuracy_score(cross_val1, y_pred))
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(cross_val1, y_pred))

ValueError: ignored

In [ ]:
#@title Classifier 6: LOGISTIC REGRESSION


In [261]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.09, solver='liblinear')
LR.fit(x_train,y_train)

LogisticRegression(C=0.09, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [262]:
LR_pred = LR.predict(x_test)

In [263]:
print(confusion_matrix(y_test, LR_pred))
print(classification_report(y_test, LR_pred))
print(accuracy_score(y_test, LR_pred))

[[14  5]
 [ 2 35]]
              precision    recall  f1-score   support

         0.0       0.88      0.74      0.80        19
         1.0       0.88      0.95      0.91        37

    accuracy                           0.88        56
   macro avg       0.88      0.84      0.85        56
weighted avg       0.88      0.88      0.87        56

0.875


In [264]:
#@title CLASSIFIER 7: GAUSSIAN


In [265]:
# import Gaussian Naive Bayes import GaussianNB
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier 
gnb = GaussianNB()

# Train the model using the training sets
gnb.fit(x_train, y_train)

# Predict the response for the test dataset
y_pred = gnb.predict(x_test)

In [266]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[13  6]
 [ 7 30]]
              precision    recall  f1-score   support

         0.0       0.65      0.68      0.67        19
         1.0       0.83      0.81      0.82        37

    accuracy                           0.77        56
   macro avg       0.74      0.75      0.74        56
weighted avg       0.77      0.77      0.77        56

0.7678571428571429


In [267]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7678571428571429


In [ ]:
#@title CLASSIFIER 8: with LDA


In [268]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X_train = lda.fit_transform(x_train, y_train)
X_test = lda.transform(x_test)

In [276]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=3)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [277]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[12  7]
 [ 2 35]]
Accuracy0.8392857142857143


In [278]:
#@title CLASSIFIER 9: PERCEPTRON


In [282]:
from sklearn.linear_model import Perceptron

In [298]:
cls= Perceptron()
cls.fit(x_train,y_train)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [299]:
y_pred = cls.predict(x_test)

In [300]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[13  6]
 [ 6 31]]
              precision    recall  f1-score   support

         0.0       0.68      0.68      0.68        19
         1.0       0.84      0.84      0.84        37

    accuracy                           0.79        56
   macro avg       0.76      0.76      0.76        56
weighted avg       0.79      0.79      0.79        56

0.7857142857142857
