<a href="https://colab.research.google.com/github/mefy-Aruna/Face-App/blob/master/DATASETcovid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
# import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df = pd.read_csv(r'covid.csv')

In [47]:
df

SESSO  AGE   WBC  Piastrine  Neutrofili  ...   ALT    ALP   GGT    LDH  TARGET
0       M   56   2.9      128.0         1.9  ...  18.0   43.0  21.0  257.0       1
1       M   56   3.5      151.0         2.1  ...  14.0   50.0  17.0  207.0       1
2       M   72   4.6      206.0         NaN  ...  22.0    NaN   NaN    NaN       1
3       M   72  16.5      316.0        14.0  ...  33.0   80.0  42.0  651.0       1
4       M   77   4.9      198.0         NaN  ...   NaN    NaN   NaN    NaN       1
..    ...  ...   ...        ...         ...  ...   ...    ...   ...    ...     ...
274     F   40   5.6      270.0         NaN  ...  29.0   78.0  20.0    NaN       0
275     M   26   4.7       44.0         NaN  ...  44.0  110.0  93.0  175.0       0
276     F   44  15.7      356.0         NaN  ...  17.0    NaN   NaN  272.0       0
277     F   41  12.0      321.0         6.7  ...  11.0  201.0  14.0  266.0       0
278     M   53  17.9      272.0        14.1  ...  10.0    NaN   NaN  258.0       0

[279 rows x 16 columns]

In [48]:
# Lets convert male to 0 and female to 1:
df['SESSO'].replace(to_replace=['M','F'], value=[0,1],inplace=True)
df.head()
df['Linfociti'] = pd.to_numeric(df['Linfociti'], errors='coerce')

In [49]:
data= pd.DataFrame(df)
data.to_csv("covid.csv", index=False, header=False)

In [50]:
df= pd.read_csv('covid.csv')

In [51]:
df

0  56   2.9  128.0   1.9  0.8  ...  36.0  18.0   43.0  21.0  257.0  1
0    0  56   3.5  151.0   2.1  0.9  ...  25.0  14.0   50.0  17.0  207.0  1
1    0  72   4.6  206.0   NaN  NaN  ...  31.0  22.0    NaN   NaN    NaN  1
2    0  72  16.5  316.0  14.0  1.2  ...  96.0  33.0   80.0  42.0  651.0  1
3    0  77   4.9  198.0   NaN  NaN  ...   NaN   NaN    NaN   NaN    NaN  1
4    0  77   3.0  162.0   2.0  0.4  ...  21.0  10.0    NaN   NaN  220.0  1
..  ..  ..   ...    ...   ...  ...  ...   ...   ...    ...   ...    ... ..
273  1  40   5.6  270.0   NaN  NaN  ...  22.0  29.0   78.0  20.0    NaN  0
274  0  26   4.7   44.0   NaN  NaN  ...  30.0  44.0  110.0  93.0  175.0  0
275  1  44  15.7  356.0   NaN  NaN  ...  31.0  17.0    NaN   NaN  272.0  0
276  1  41  12.0  321.0   6.7  2.3  ...  16.0  11.0  201.0  14.0  266.0  0
277  0  53  17.9  272.0  14.1  2.1  ...  13.0  10.0    NaN   NaN  258.0  0

[278 rows x 16 columns]

In [ ]:
####### 1.KNN IMPUTER########################
..................
..............................


In [52]:
from fancyimpute import KNN

In [53]:
df1= pd.read_csv('covid.csv')

In [54]:
df1

0  56   2.9  128.0   1.9  0.8  ...  36.0  18.0   43.0  21.0  257.0  1
0    0  56   3.5  151.0   2.1  0.9  ...  25.0  14.0   50.0  17.0  207.0  1
1    0  72   4.6  206.0   NaN  NaN  ...  31.0  22.0    NaN   NaN    NaN  1
2    0  72  16.5  316.0  14.0  1.2  ...  96.0  33.0   80.0  42.0  651.0  1
3    0  77   4.9  198.0   NaN  NaN  ...   NaN   NaN    NaN   NaN    NaN  1
4    0  77   3.0  162.0   2.0  0.4  ...  21.0  10.0    NaN   NaN  220.0  1
..  ..  ..   ...    ...   ...  ...  ...   ...   ...    ...   ...    ... ..
273  1  40   5.6  270.0   NaN  NaN  ...  22.0  29.0   78.0  20.0    NaN  0
274  0  26   4.7   44.0   NaN  NaN  ...  30.0  44.0  110.0  93.0  175.0  0
275  1  44  15.7  356.0   NaN  NaN  ...  31.0  17.0    NaN   NaN  272.0  0
276  1  41  12.0  321.0   6.7  2.3  ...  16.0  11.0  201.0  14.0  266.0  0
277  0  53  17.9  272.0  14.1  2.1  ...  13.0  10.0    NaN   NaN  258.0  0

[278 rows x 16 columns]

In [55]:
knn_imputer = KNN(10) #use 10 nearest rows which have a feature to fill in each

In [56]:
df1= knn_imputer.fit_transform(df1)

Imputing row 1/278 with 0 missing, elapsed time: 0.024
Imputing row 101/278 with 0 missing, elapsed time: 0.028
Imputing row 201/278 with 8 missing, elapsed time: 0.031


In [57]:
df1

array([[  0.        ,  56.        ,   3.5       , ...,  17.        ,
        207.        ,   1.        ],
       [  0.        ,  72.        ,   4.6       , ...,  41.47834349,
        275.91981709,   1.        ],
       [  0.        ,  72.        ,  16.5       , ...,  42.        ,
        651.        ,   1.        ],
       ...,
       [  1.        ,  44.        ,  15.7       , ...,  36.35523013,
        272.        ,   0.        ],
       [  1.        ,  41.        ,  12.        , ...,  14.        ,
        266.        ,   0.        ],
       [  0.        ,  53.        ,  17.9       , ...,  32.0518687 ,
        258.        ,   0.        ]])

In [58]:
data = pd.DataFrame(df1)
data.to_csv("KNN_dataset.csv")

In [59]:
df1 = pd.read_csv(r'KNN_dataset.csv')

In [60]:
df1

Unnamed: 0    0     1     2  ...          12          13          14   15
0             0  0.0  56.0   3.5  ...   50.000000   17.000000  207.000000  1.0
1             1  0.0  72.0   4.6  ...   68.675596   41.478343  275.919817  1.0
2             2  0.0  72.0  16.5  ...   80.000000   42.000000  651.000000  1.0
3             3  0.0  77.0   4.9  ...  187.820464  198.913673  340.157876  1.0
4             4  0.0  77.0   3.0  ...   56.314318   40.091000  220.000000  1.0
..          ...  ...   ...   ...  ...         ...         ...         ...  ...
273         273  1.0  40.0   5.6  ...   78.000000   20.000000  244.218394  0.0
274         274  0.0  26.0   4.7  ...  110.000000   93.000000  175.000000  0.0
275         275  1.0  44.0  15.7  ...   99.147738   36.355230  272.000000  0.0
276         276  1.0  41.0  12.0  ...  201.000000   14.000000  266.000000  0.0
277         277  0.0  53.0  17.9  ...   81.998967   32.051869  258.000000  0.0

[278 rows x 17 columns]

In [ ]:
########## 2.Itertive Imputer as MICE IMPUTER #############
.............
.....................
.........................
....................


In [61]:
from fancyimpute import IterativeImputer

In [63]:
dataset= pd.read_csv('covid.csv')

In [64]:
mice_impute = IterativeImputer()

In [65]:
df2 = mice_impute.fit_transform(dataset)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [66]:
df2

array([[  0.        ,  56.        ,   3.5       , ...,  17.        ,
        207.        ,   1.        ],
       [  0.        ,  72.        ,   4.6       , ...,  50.3239521 ,
        401.96762603,   1.        ],
       [  0.        ,  72.        ,  16.5       , ...,  42.        ,
        651.        ,   1.        ],
       ...,
       [  1.        ,  44.        ,  15.7       , ...,  55.46432938,
        272.        ,   0.        ],
       [  1.        ,  41.        ,  12.        , ...,  14.        ,
        266.        ,   0.        ],
       [  0.        ,  53.        ,  17.9       , ..., -21.61810601,
        258.        ,   0.        ]])

In [68]:
data = pd.DataFrame(df2)
data.to_csv("MICE_dataset.csv")

In [69]:
df2= pd.read_csv('MICE_dataset.csv')

In [70]:
df2

Unnamed: 0    0     1     2  ...          12         13          14   15
0             0  0.0  56.0   3.5  ...   50.000000  17.000000  207.000000  1.0
1             1  0.0  72.0   4.6  ...   63.527102  50.323952  401.967626  1.0
2             2  0.0  72.0  16.5  ...   80.000000  42.000000  651.000000  1.0
3             3  0.0  77.0   4.9  ...   68.970952  90.044752  372.035248  1.0
4             4  0.0  77.0   3.0  ...   89.363302  54.137925  220.000000  1.0
..          ...  ...   ...   ...  ...         ...        ...         ...  ...
273         273  1.0  40.0   5.6  ...   78.000000  20.000000  237.294739  0.0
274         274  0.0  26.0   4.7  ...  110.000000  93.000000  175.000000  0.0
275         275  1.0  44.0  15.7  ...  109.003091  55.464329  272.000000  0.0
276         276  1.0  41.0  12.0  ...  201.000000  14.000000  266.000000  0.0
277         277  0.0  53.0  17.9  ...   50.263803 -21.618106  258.000000  0.0

[278 rows x 17 columns]

In [ ]:
############ 3.MULTIPLE IMPUTER ##############
.............
......................
....................
.............................


In [72]:
pip install autoimpute

     |████████████████████████████████| 102kB 2.7MB/s 


In [73]:
from autoimpute.imputations import MultipleImputer

In [74]:
multiImputer= MultipleImputer()

In [76]:
df3= multiImputer.fit_transform(dataset)

In [77]:
df3

<generator object MultipleImputer.transform.<locals>.<genexpr> at 0x7ff71b002e08>

In [78]:
data = pd.DataFrame(df3)
data.to_csv("MULTI_dataset.csv")

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
Sequential sampling (2 chains in 1 job)
NUTS: [σ, beta, alpha]
100%|██████████| 2000/2000 [00:33<00:00, 59.65it/s]
The acceptance probability does not match the target. It is 0.9219932102547636, but should be close to 0.8. Try to increase the number of tuning steps.
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [σ, beta, alpha]
100%|██████████| 2000/2000 [00:11<00:00, 168.55it/s]
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains

ValueError: ignored

In [ ]:
#####################4. NuclearNormMinimization######
# matrix completion using convex optimization to find low-rank solution
# that still matches observed values. Slow!
.......................
...................................
...........................................


In [79]:
from fancyimpute import KNN, NuclearNormMinimization, SoftImpute, BiScaler


In [81]:
df4= pd.read_csv(r'covid.csv')

In [82]:
df4 = NuclearNormMinimization().fit_transform(df4)

----------------------------------------------------------------------------
	SCS v2.1.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 72995
eps = 1.00e-04, alpha = 1.50, max_iters = 50000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 52261, constraints m = 61157
Cones:	primal zero / dual free vars: 4448
	linear vars: 13344
	sd vars: 43365, sd blks: 1
Setup time: 9.54e-02s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 2.99e+21  2.77e+21  1.00e+00 -2.15e+26  4.14e+25  6.23e+25  5.42e-02 
   100| 5.77e-04  6.53e-04  3.02e-04  1.53e+04  1.53e+04  7.45e-12  7.29e+00 
   200| 2.71e-04  2.80e-04  1.02e-04  1.53e+04  1.53e

In [83]:
df4

array([[  0.        ,  56.        ,   3.5       , ...,  17.        ,
        207.        ,   1.        ],
       [  0.        ,  72.        ,   4.6       , ...,  35.08706593,
        221.91363589,   1.        ],
       [  0.        ,  72.        ,  16.5       , ...,  42.        ,
        651.        ,   1.        ],
       ...,
       [  1.        ,  44.        ,  15.7       , ...,  51.58303801,
        272.        ,   0.        ],
       [  1.        ,  41.        ,  12.        , ...,  14.        ,
        266.        ,   0.        ],
       [  0.        ,  53.        ,  17.9       , ...,  35.0529378 ,
        258.        ,   0.        ]])

In [87]:
data= pd.DataFrame(df4)
data.to_csv('Nuclear_dataset.csv',index=False,header = False)

In [88]:
df4= pd.read_csv('Nuclear_dataset.csv')

In [89]:
df4

0  0.0  56.0   3.5  ...        50.0       17.0       207.0  1.0
0      1  0.0  72.0   4.6  ...   46.726832  35.087066  221.913636  1.0
1      2  0.0  72.0  16.5  ...   80.000000  42.000000  651.000000  1.0
2      3  0.0  77.0   4.9  ...   42.839245  29.537535  155.606616  1.0
3      4  0.0  77.0   3.0  ...   45.463065  27.389495  220.000000  1.0
4      5  0.0  74.0   5.3  ...   42.093793  27.000000  117.000000  1.0
..   ...  ...   ...   ...  ...         ...        ...         ...  ...
272  273  1.0  40.0   5.6  ...   78.000000  20.000000  168.596827  0.0
273  274  0.0  26.0   4.7  ...  110.000000  93.000000  175.000000  0.0
274  275  1.0  44.0  15.7  ...   69.910167  51.583038  272.000000  0.0
275  276  1.0  41.0  12.0  ...  201.000000  14.000000  266.000000  0.0
276  277  0.0  53.0  17.9  ...   56.395485  35.052938  258.000000  0.0

[277 rows x 17 columns]

In [ ]:
##########4. Nuclear with dataset variable #####
.............
......................
.......................


In [111]:
df4 = NuclearNormMinimization().fit_transform(dataset)

----------------------------------------------------------------------------
	SCS v2.1.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 72995
eps = 1.00e-04, alpha = 1.50, max_iters = 50000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 52261, constraints m = 61157
Cones:	primal zero / dual free vars: 4448
	linear vars: 13344
	sd vars: 43365, sd blks: 1
Setup time: 6.09e-02s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 2.99e+21  2.77e+21  1.00e+00 -2.15e+26  4.14e+25  6.23e+25  4.15e-02 
   100| 5.77e-04  6.53e-04  3.02e-04  1.53e+04  1.53e+04  7.45e-12  7.22e+00 
   200| 2.71e-04  2.80e-04  1.02e-04  1.53e+04  1.53e

In [112]:
df4

array([[  0.        ,  56.        ,   3.5       , ...,  17.        ,
        207.        ,   1.        ],
       [  0.        ,  72.        ,   4.6       , ...,  35.08706593,
        221.91363589,   1.        ],
       [  0.        ,  72.        ,  16.5       , ...,  42.        ,
        651.        ,   1.        ],
       ...,
       [  1.        ,  44.        ,  15.7       , ...,  51.58303801,
        272.        ,   0.        ],
       [  1.        ,  41.        ,  12.        , ...,  14.        ,
        266.        ,   0.        ],
       [  0.        ,  53.        ,  17.9       , ...,  35.0529378 ,
        258.        ,   0.        ]])

In [113]:
data=pd.DataFrame(df4)
data.to_csv('Nuclear_datasetprevvariable.csv')

In [114]:
df4= pd.read_csv('Nuclear_datasetprevvariable.csv')

In [115]:
df4

Unnamed: 0    0     1     2  ...          12         13          14   15
0             0  0.0  56.0   3.5  ...   50.000000  17.000000  207.000000  1.0
1             1  0.0  72.0   4.6  ...   46.726832  35.087066  221.913636  1.0
2             2  0.0  72.0  16.5  ...   80.000000  42.000000  651.000000  1.0
3             3  0.0  77.0   4.9  ...   42.839245  29.537535  155.606616  1.0
4             4  0.0  77.0   3.0  ...   45.463065  27.389495  220.000000  1.0
..          ...  ...   ...   ...  ...         ...        ...         ...  ...
273         273  1.0  40.0   5.6  ...   78.000000  20.000000  168.596827  0.0
274         274  0.0  26.0   4.7  ...  110.000000  93.000000  175.000000  0.0
275         275  1.0  44.0  15.7  ...   69.910167  51.583038  272.000000  0.0
276         276  1.0  41.0  12.0  ...  201.000000  14.000000  266.000000  0.0
277         277  0.0  53.0  17.9  ...   56.395485  35.052938  258.000000  0.0

[278 rows x 17 columns]

In [ ]:
##############5. SOFT IMPUTE #########################
..............
...............................
....................................


In [116]:
from fancyimpute import SoftImpute, BiScaler


In [122]:

#X_incomplete_normalized = BiScaler().fit_transform(dataset)
df5 = SoftImpute().fit_transform(dataset)


[SoftImpute] Max Singular Value of X_init = 7162.538699
[SoftImpute] Iter 1: observed MAE=3.536283 rank=8
[SoftImpute] Iter 2: observed MAE=3.541678 rank=8
[SoftImpute] Iter 3: observed MAE=3.551385 rank=8
[SoftImpute] Iter 4: observed MAE=3.558222 rank=8
[SoftImpute] Iter 5: observed MAE=3.562449 rank=8
[SoftImpute] Iter 6: observed MAE=3.565367 rank=8
[SoftImpute] Iter 7: observed MAE=3.567335 rank=8
[SoftImpute] Iter 8: observed MAE=3.568674 rank=8
[SoftImpute] Iter 9: observed MAE=3.569406 rank=8
[SoftImpute] Iter 10: observed MAE=3.569905 rank=8
[SoftImpute] Iter 11: observed MAE=3.570132 rank=8
[SoftImpute] Iter 12: observed MAE=3.570154 rank=8
[SoftImpute] Iter 13: observed MAE=3.570210 rank=8
[SoftImpute] Iter 14: observed MAE=3.570490 rank=8
[SoftImpute] Iter 15: observed MAE=3.570701 rank=8
[SoftImpute] Iter 16: observed MAE=3.570880 rank=8
[SoftImpute] Iter 17: observed MAE=3.571050 rank=8
[SoftImpute] Iter 18: observed MAE=3.571214 rank=8
[SoftImpute] Iter 19: observed MAE=

In [123]:
df5

array([[  0.        ,  56.        ,   3.5       , ...,  17.        ,
        207.        ,   1.        ],
       [  0.        ,  72.        ,   4.6       , ...,  33.03970516,
        207.75312832,   1.        ],
       [  0.        ,  72.        ,  16.5       , ...,  42.        ,
        651.        ,   1.        ],
       ...,
       [  1.        ,  44.        ,  15.7       , ...,  51.56335242,
        272.        ,   0.        ],
       [  1.        ,  41.        ,  12.        , ...,  14.        ,
        266.        ,   0.        ],
       [  0.        ,  53.        ,  17.9       , ...,  35.24872102,
        258.        ,   0.        ]])

In [124]:
data= pd.DataFrame(df5)

In [128]:
data.to_csv('Soft_dataset.csv',index=False,header=False)

In [129]:
df5= pd.read_csv(r'Soft_dataset.csv')

In [130]:
df5

0.0  56.0   3.5  151.0  ...        50.0       17.0       207.0  1.0
0    0.0  72.0   4.6  206.0  ...   45.647435  33.039705  207.753128  1.0
1    0.0  72.0  16.5  316.0  ...   80.000000  42.000000  651.000000  1.0
2    0.0  77.0   4.9  198.0  ...   41.536732  27.098526  142.624122  1.0
3    0.0  77.0   3.0  162.0  ...   45.476430  26.635762  220.000000  1.0
4    0.0  74.0   5.3  189.0  ...   42.336365  27.000000  117.000000  1.0
..   ...   ...   ...    ...  ...         ...        ...         ...  ...
272  1.0  40.0   5.6  270.0  ...   78.000000  20.000000  158.833478  0.0
273  0.0  26.0   4.7   44.0  ...  110.000000  93.000000  175.000000  0.0
274  1.0  44.0  15.7  356.0  ...   68.974162  51.563352  272.000000  0.0
275  1.0  41.0  12.0  321.0  ...  201.000000  14.000000  266.000000  0.0
276  0.0  53.0  17.9  272.0  ...   55.686893  35.248721  258.000000  0.0

[277 rows x 16 columns]

In [ ]:
######### 6.