<a href="https://colab.research.google.com/github/mefy-Aruna/Face-App/blob/master/MicedatasetClassifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [117]:
df = pd.read_csv(r'MICE_dataset.csv')
df

Unnamed: 0    0     1     2  ...          12         13          14   15
0             0  0.0  56.0   3.5  ...   50.000000  17.000000  207.000000  1.0
1             1  0.0  72.0   4.6  ...   63.527102  50.323952  401.967626  1.0
2             2  0.0  72.0  16.5  ...   80.000000  42.000000  651.000000  1.0
3             3  0.0  77.0   4.9  ...   68.970952  90.044752  372.035248  1.0
4             4  0.0  77.0   3.0  ...   89.363302  54.137925  220.000000  1.0
..          ...  ...   ...   ...  ...         ...        ...         ...  ...
273         273  1.0  40.0   5.6  ...   78.000000  20.000000  237.294739  0.0
274         274  0.0  26.0   4.7  ...  110.000000  93.000000  175.000000  0.0
275         275  1.0  44.0  15.7  ...  109.003091  55.464329  272.000000  0.0
276         276  1.0  41.0  12.0  ...  201.000000  14.000000  266.000000  0.0
277         277  0.0  53.0  17.9  ...   50.263803 -21.618106  258.000000  0.0

[278 rows x 17 columns]

In [118]:
df

Unnamed: 0    0     1     2  ...          12         13          14   15
0             0  0.0  56.0   3.5  ...   50.000000  17.000000  207.000000  1.0
1             1  0.0  72.0   4.6  ...   63.527102  50.323952  401.967626  1.0
2             2  0.0  72.0  16.5  ...   80.000000  42.000000  651.000000  1.0
3             3  0.0  77.0   4.9  ...   68.970952  90.044752  372.035248  1.0
4             4  0.0  77.0   3.0  ...   89.363302  54.137925  220.000000  1.0
..          ...  ...   ...   ...  ...         ...        ...         ...  ...
273         273  1.0  40.0   5.6  ...   78.000000  20.000000  237.294739  0.0
274         274  0.0  26.0   4.7  ...  110.000000  93.000000  175.000000  0.0
275         275  1.0  44.0  15.7  ...  109.003091  55.464329  272.000000  0.0
276         276  1.0  41.0  12.0  ...  201.000000  14.000000  266.000000  0.0
277         277  0.0  53.0  17.9  ...   50.263803 -21.618106  258.000000  0.0

[278 rows x 17 columns]

In [119]:
x = df.iloc[:, 1:16].values
y = df.iloc[:, 16].values

In [120]:
x


array([[  0.        ,  56.        ,   3.5       , ...,  50.        ,
         17.        , 207.        ],
       [  0.        ,  72.        ,   4.6       , ...,  63.52710171,
         50.3239521 , 401.96762603],
       [  0.        ,  72.        ,  16.5       , ...,  80.        ,
         42.        , 651.        ],
       ...,
       [  1.        ,  44.        ,  15.7       , ..., 109.00309115,
         55.46432938, 272.        ],
       [  1.        ,  41.        ,  12.        , ..., 201.        ,
         14.        , 266.        ],
       [  0.        ,  53.        ,  17.9       , ...,  50.26380301,
        -21.61810601, 258.        ]])

In [ ]:
######### KNN IMPUTED DATASET


////////////////////////////

In [ ]:
#@title CLASSIFIER1:KNN


In [121]:
# Train Test Split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier



In [122]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [138]:
x_train

array([[ 1.48909076,  1.06482039,  0.44952996, ..., -0.37580152,
        -0.63751765,  0.28832271],
       [-0.67155074,  0.83697448,  2.99746352, ...,  1.15757937,
         0.40963928,  1.85634313],
       [-0.67155074, -1.78325342, -0.08044022, ..., -0.42602029,
        -0.60320545, -0.86090965],
       ...,
       [-0.67155074,  1.06482039, -1.05884671, ..., -0.41784882,
        -0.21829322, -0.43763998],
       [-0.67155074,  1.06482039,  0.06224406, ..., -0.18748113,
        -0.57747131,  0.02348365],
       [-0.67155074, -0.24529356, -0.63079387, ..., -0.47623906,
        -0.51742496, -0.2229883 ]])

In [123]:
# Preprocessing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [124]:
KNNclassifier = KNeighborsClassifier(n_neighbors = 20)
KNNclassifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                     weights='uniform')

In [125]:
y_pred = KNNclassifier.predict(x_test)

In [126]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('KNN acc:',accuracy_score(y_test, y_pred))

[[17  6]
 [ 6 27]]
              precision    recall  f1-score   support

         0.0       0.74      0.74      0.74        23
         1.0       0.82      0.82      0.82        33

    accuracy                           0.79        56
   macro avg       0.78      0.78      0.78        56
weighted avg       0.79      0.79      0.79        56

KNN acc: 0.7857142857142857


In [ ]:
#@title CLASSIFIER 2:DECISION TREE





In [ ]:
#from sklearn.model_selection import train_test_split
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [127]:
from sklearn.tree import DecisionTreeClassifier
Decclassifier = DecisionTreeClassifier(criterion="entropy", max_depth = 5)
Decclassifier 

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [128]:

Decclassifier.fit(x_train,y_train)
y_pred = Decclassifier.predict(x_test)

In [129]:
from sklearn import metrics
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, y_pred))

DecisionTrees's Accuracy:  0.8035714285714286


In [130]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('DecisionTree acc:',accuracy_score(y_test, y_pred))

[[21  2]
 [ 9 24]]
              precision    recall  f1-score   support

         0.0       0.70      0.91      0.79        23
         1.0       0.92      0.73      0.81        33

    accuracy                           0.80        56
   macro avg       0.81      0.82      0.80        56
weighted avg       0.83      0.80      0.80        56

DecisionTree acc: 0.8035714285714286


In [ ]:
#@title CLASSIFIER 3:SVM


In [131]:

# Polynomial Kernel
from sklearn.svm import SVC   # Support Vector Classifier
SVMclassifier = SVC(kernel ='rbf')
SVMclassifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [139]:
x_train

array([[ 1.48909076,  1.06482039,  0.44952996, ..., -0.37580152,
        -0.63751765,  0.28832271],
       [-0.67155074,  0.83697448,  2.99746352, ...,  1.15757937,
         0.40963928,  1.85634313],
       [-0.67155074, -1.78325342, -0.08044022, ..., -0.42602029,
        -0.60320545, -0.86090965],
       ...,
       [-0.67155074,  1.06482039, -1.05884671, ..., -0.41784882,
        -0.21829322, -0.43763998],
       [-0.67155074,  1.06482039,  0.06224406, ..., -0.18748113,
        -0.57747131,  0.02348365],
       [-0.67155074, -0.24529356, -0.63079387, ..., -0.47623906,
        -0.51742496, -0.2229883 ]])

In [132]:
y_pred = SVMclassifier.predict(x_test)

In [134]:
# Evaluating the Algorithm
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[17  6]
 [ 5 28]]
              precision    recall  f1-score   support

         0.0       0.77      0.74      0.76        23
         1.0       0.82      0.85      0.84        33

    accuracy                           0.80        56
   macro avg       0.80      0.79      0.80        56
weighted avg       0.80      0.80      0.80        56

0.8035714285714286


In [ ]:
#@title Classifier 4: Random Forest 


In [135]:
# Train the Algorithm
from sklearn.ensemble import RandomForestClassifier
RFclassifier = RandomForestClassifier(n_estimators = 20)
RFclassifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [136]:

y_pred = RFclassifier.predict(x_test)

In [137]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[19  4]
 [ 2 31]]
              precision    recall  f1-score   support

         0.0       0.90      0.83      0.86        23
         1.0       0.89      0.94      0.91        33

    accuracy                           0.89        56
   macro avg       0.90      0.88      0.89        56
weighted avg       0.89      0.89      0.89        56

0.8928571428571429


In [166]:
# Train the Algorithm
RF1classifier = RandomForestClassifier(n_estimators = 75)
RF1classifier.fit(x_train, y_train)

y_pred = RF1classifier.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[18  5]
 [ 3 30]]
              precision    recall  f1-score   support

         0.0       0.86      0.78      0.82        23
         1.0       0.86      0.91      0.88        33

    accuracy                           0.86        56
   macro avg       0.86      0.85      0.85        56
weighted avg       0.86      0.86      0.86        56

0.8571428571428571


In [149]:
#@title Classifier 5: Random Forest regressor


In [167]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [168]:
forest = RandomForestRegressor(n_estimators=100)

In [169]:
cross_val1 = cross_val_score(forest, x_train,y_train, cv=56)  

In [170]:
forest = forest.fit(x_train, y_train)

In [171]:
y_pred = forest.predict(x_test)

In [172]:
#print(confusion_matrix(y_test, y_pred))
#print(classification_report(y_test, y_pred))
#print(accuracy_score(cross_val1, y_pred))
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(cross_val1, y_pred))

ValueError: ignored

In [ ]:
#@title Classifier 6: LOGISTIC REGRESSION


In [207]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.009, solver='liblinear')
LR.fit(x_train,y_train)

LogisticRegression(C=0.009, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [208]:
LR_pred = LR.predict(x_test)

In [209]:
print(confusion_matrix(y_test, LR_pred))
print(classification_report(y_test, LR_pred))
print(accuracy_score(y_test, LR_pred))

[[18  5]
 [ 9 24]]
              precision    recall  f1-score   support

         0.0       0.67      0.78      0.72        23
         1.0       0.83      0.73      0.77        33

    accuracy                           0.75        56
   macro avg       0.75      0.75      0.75        56
weighted avg       0.76      0.75      0.75        56

0.75


In [ ]:
#@title CLASSIFIER 7: GAUSSIAN


In [210]:
# import Gaussian Naive Bayes import GaussianNB
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier 
gnb = GaussianNB()

# Train the model using the training sets
gnb.fit(x_train, y_train)

# Predict the response for the test dataset
y_pred = gnb.predict(x_test)

In [211]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[19  4]
 [12 21]]
              precision    recall  f1-score   support

         0.0       0.61      0.83      0.70        23
         1.0       0.84      0.64      0.72        33

    accuracy                           0.71        56
   macro avg       0.73      0.73      0.71        56
weighted avg       0.75      0.71      0.72        56

0.7142857142857143


In [212]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7142857142857143


In [ ]:
#@title CLASSIFIER 8: with LDA


In [213]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X_train = lda.fit_transform(x_train, y_train)
X_test = lda.transform(x_test)

In [224]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=100)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [225]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[17  6]
 [ 5 28]]
Accuracy0.8035714285714286


In [ ]:
#@title CLASSIFIER 9: PERCEPTRON


In [226]:
from sklearn.linear_model import Perceptron

In [227]:
cls= Perceptron()
cls.fit(x_train,y_train)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [228]:
y_pred = cls.predict(x_test)

In [229]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[13 10]
 [ 8 25]]
              precision    recall  f1-score   support

         0.0       0.62      0.57      0.59        23
         1.0       0.71      0.76      0.74        33

    accuracy                           0.68        56
   macro avg       0.67      0.66      0.66        56
weighted avg       0.68      0.68      0.68        56

0.6785714285714286
